# Uncomment the next line to define a global platform for your project
platform :ios, '13.0'

target 'Paws Go 5' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Paws Go 5
	pod 'Firebase/Auth'
    pod 'Firebase/Firestore'
    pod 'Firebase/Storage'
    pod 'FirebaseFirestoreSwift'
    pod 'Firebase/Functions'
    pod 'GoogleMaps'
    pod 'GooglePlaces'

  target 'Paws Go 5Tests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'Paws Go 5UITests' do
    # Pods for testing
  end

end
